spring.application.name=DEBUGGERS_BLOCKCHAIN

spring.datasource.url=jdbc:oracle:thin:@//fsktmdbora.upm.edu.my:1521/fsktm
spring.datasource.username=D230405
spring.datasource.password=230405
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true